// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearChat():Promise<void>;

export function SendMessage(arg1:string,arg2:number):Promise<main.ChatResponse>;
